name: Secure CI/CD Pipeline

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  security-checks:

    runs-on: ubuntu-latest

    permissions:
      contents: read
      security-events: write

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Show Files
        run: ls -la

      - name: Display Current Directory
        run: pwd

      - name: GitHub Runner Info
        run: uname -a